// <auto-generated />
using System;
using ApiReseñaValoracion.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiReseñaValoracion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231117032918_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiReseñaValoracion.Models.Reseña", b =>
                {
                    b.Property<int>("ReseñaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReseñaId"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("ValoracionId")
                        .HasColumnType("int");

                    b.HasKey("ReseñaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ValoracionId");

                    b.ToTable("Resenas");
                });

            modelBuilder.Entity("ApiReseñaValoracion.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ApiReseñaValoracion.Models.Valoracion", b =>
                {
                    b.Property<int>("ValoracionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ValoracionId"), 1L, 1);

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("ValoracionId");

                    b.ToTable("Valoraciones");
                });

            modelBuilder.Entity("ApiReseñaValoracion.Models.Reseña", b =>
                {
                    b.HasOne("ApiReseñaValoracion.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiReseñaValoracion.Models.Valoracion", "Valoracion")
                        .WithMany()
                        .HasForeignKey("ValoracionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Valoracion");
                });
#pragma warning restore 612, 618
        }
    }
}
